# Компилятор и флаги
CXX = g++
CXXFLAGS = -std=c++20 -O0 -g -fprofile-arcs -ftest-coverage
LDFLAGS = -lgtest -lgtest_main -pthread

SRC = main.cpp
BIN = app
TEST_BIN = test
COVERAGE_XML = coverage.cobertura.xml

# Собирает основное приложение (без тестов)
all: $(BIN)

$(BIN): $(SRC)
	$(CXX) $(CXXFLAGS) $(SRC) -o $(BIN)

# Компиляция и запуск тестов с флагом RUN_TESTS
test:
	$(CXX) $(CXXFLAGS) -DRUN_TESTS $(SRC) -o $(TEST_BIN) $(LDFLAGS)
	./$(TEST_BIN)

# Генерация отчёта покрытия (исключаем main)
coverage: test
	gcovr --root . --xml-pretty -o $(COVERAGE_XML) --exclude='main.cpp'

# Удаление бинарников и файлов покрытия
clean:
	rm -f $(BIN) $(TEST_BIN) *.gcno *.gcda $(COVERAGE_XML)
